name: Copy PRs to source

on:
  pull_request:
    branches:
      - develop

jobs:
  on_pr_to_develop:
    if: github.actor == 'edwin-focaloid'
    runs-on: ubuntu-latest
    steps:
      - name: Get PR number
        run: |
          echo "here is the PR number"
          echo  ${{ github.event.pull_request.number }}
