name: Copy PRs to source

on:
  pull_request:
    branches:
      - develop

jobs:
  on_pr_to_develop:
    if: github.actor != 'edwin-focaloid'
    runs-on: ubuntu-latest
    steps:
       - name: Clone remote repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0   

      - name: Get PR number
        run: |
          echo "here is the PR number"
          time=$(date +"%I-%M-%S_%d-%m-%Y")
          wget "https://github.com/oat-sa/test-public1-repo/pull/${{ github.event.pull_request.number }}.patch"
          git apply "${{ github.event.pull_request.number }}.patch"
          rm -rf "${{ github.event.pull_request.number }}.patch"
          git checkout -b "add_public_pr-$time"
          git add .
          git commit -m "fix: adding changes from public"
          git push -u origin "add_public_pr-$time":"add_public_pr-$time"
           
