name: remove me

on:
  workflow_dispatch:


jobs:
  send_repository_dispatch: 
    runs-on: ubuntu-latest     
    steps:

        - name: get commit and PR number 
          id: fetch_details
          run : | 
            echo "test"