name: pull request changes from community

on:
  repository_dispatch:
    types: [pull-changes-from-community]

jobs:
  cherry-picking:
    runs-on: ubuntu-latest
    env:
      GH_TOKEN: ${{ secrets.AUTOMATED_USER_TOKEN }}     
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set Git user information
        run: |
          git config --global user.email "happybot+devops@taotesting.com"
          git config --global user.name "HappyBot"   
          
          
      - name: Create New Branch
        run: |
            git checkout -b testing-cherry-pick-${{ github.event.client_payload.pr_num }}



      - name: Fetch PR Changes
        run: |
            git remote add upstream-public git@github.com:oat-sa/test-public1-repo.git
            git fetch upstream-public pull/${{ github.event.client_payload.pr_num }}/head

            git cherry-pick  ${{ github.event.client_payload.commit_sha }}..FETCH_HEAD || true

            git push origin "testing-cherry-pick-${{ github.event.client_payload.pr_num }}:testing-cherry-pick-${{ github.event.client_payload.pr_num }}"

      - name: create PR
        run: | 
            gh pr create --base main --head testing-cherry-pick-${{ github.event.client_payload.pr_num }} --title "community PR ${{ github.event.client_payload.pr_num }}" --body "review requested changes"
          
            echo "PR created successfully"
