name: Push cnanges to private

on:
  pull_request:
    types:
      - closed

jobs:
  push-changes:
    runs-on: ubuntu-latest

    if: github.event.pull_request.merged == true
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set Git user information
      run: |
        git config --global user.email "happybot+devops@taotesting.com"
        git config --global user.name "HappyBot"
        
    - name: Create New Branch
      run: |
        git checkout -b new-feature-branch

    - name: Fetch PR Changes
      run: |
        pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
        destination_branch=test-cherry-pick
        git fetch origin $destination_branch
        git fetch origin "pull/$pr_number/head:pr-branch"
  
    - name: Cherry Pick Changes
      run: |
        git cherry-pick $destination_branch..pr-branch || true

    - name: Push New Branch
      run: |
        git push origin new-feature-branch

    ###- name: Rebase on the latest config/versions
    ###  run: |
    ###    set -eux
###
    ###    git fetch origin main
    ###    git rebase origin/main
###
    ###- name: Cherry-pick changes
    ###  run: |
    ###    git checkout -b cherry-pick-branch
    ###    git fetch origin pull/${{ github.event.pull_request.number }}/head:test-cherry-pick
    ###    git cherry-pick -m 1 FETCH_HEAD
    ###    git push origin cherry-pick-branch
           