name: send repository dispacth on private
on:
    pull_request:
      branches:
        - 'develop'
      types: [opened,synchronize]


jobs:
  send_repository_dispatch: 
    if: github.actor != 'edwin-focaloid'
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.AUTOMATED_USER_TOKEN }}       
    steps:
      - name: Checkout code
        uses: actions/checkout@v3      
        with: 
          repository: oat-sa/test-public1-repo
                 
        
      - name: Set Git user information
        run: |
          git config --global user.email "happybot+devops@taotesting.com"
          git config --global user.name "HappyBot"


      - name: get commit and PR number 
        id: fetch_details
        run : | 
          echo ${{ github.repository }}
          git fetch origin develop
          git checkout develop
          echo "last_commit=$(git log -1  | grep commit | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo $last_commit
          echo "pr_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")" >> $GITHUB_OUTPUT
        
        
      - name: Send repository_dispatch event      
        env:
          DISPATCH: ${{ secrets.MY_TOKEN }}
        run: |   
          curl -L -X POST -H "Accept: application/vnd.github+json" -H "Authorization: ${{ env.DISPATCH }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/oat-sa/test-private-repo/dispatches -d '{"event_type":"pull-changes-from-community","client_payload":{"pr_num": "${{ steps.fetch_details.outputs.pr_number }}", "commit_sha": "${{ steps.fetch_details.outputs.last_commit }}"}}'

        # uses: peter-evans/repository-dispatch@v2 #this is not reflected
        # with:
        #   # token:  "${{env.env1}}${{env.env2}}${{env.env3}}"
        #   token: '${{ env.DISPATCH }}'
        #   repository: oat-sa/test-private-repo
        #   event-type: pull-changes-from-community
        #   client-payload: '{"pr_num": "${{ steps.fetch_details.outputs.pr_number }}", "commit_sha": "${{ steps.fetch_details.outputs.last_commit }}" }'